### ISSUE TITLE
GIF in HowToPlay screen

### ISSUE THREAD

**Issue by mariaLeoveanu** [shoxtrem/RPGQuiz#12]

**Comment by bytao7mao** [comment]
ok, i can add this feature but first i need some suggestions about the actually gif.
I will put a placeholder for it and add the right gif in the future.

**Comment by FabioGouveia** [comment]
I think we can start think about some caracters images in portable network format, its not recommended to use graphic internet format on android and we can archive better results using canvas or typed arrays.
