### ISSUE TITLE
Create Question model

### ISSUE THREAD

**Issue by FabioGouveia** [shoxtrem/RPGQuiz#15]
For Level object to properly work I propose to create a Question model.
Level object need's to work with several instances of this question class. 
This issue is related to: 

Create Level model #issue14

My proposal for the initial template is:

Data members:
- **question** : String "textual question"
- **possibleAnswer** : String[] "Array of possible answers"
- **possibleAnswerState** : boolean[] "Array of possible answers state"
- **passed** : boolean " Question passed state "

API mutators:
+ **setQuestion**( question:String) : void "Set up a textual question"
+ **setPassed**( passed : boolean) : void "Set up the passed state"

API acessors:
+ **Question**(question:String, possibleAnswer : String[], possibleAnswerState : boolean[], passed:boolean) :Question "Return a new question instance"
+ **getQuestion** :String "Return a textual question"
+ **passed** : boolean "Return the passed state"
+ **verifyAnswer**( answer : String ) : boolean "Return if this answer is the correct answer"
+ **verifyAnswer**( answer : String[] ) : boolean "Return if this group of answers are the correct answers"

**Comment by Bwaim** [comment]
I started something like that, we will adjust the content with what i have done when i'll merge my contribution.

**Comment by FabioGouveia** [comment]
OK.... ;)

**Comment by Bwaim** [comment]
close with the Pull Request #21
