### ISSUE TITLE
Add a different app logo

### ISSUE THREAD

**Issue by mariaLeoveanu** [shoxtrem/RPGQuiz#16]

**Comment by EslamNagyAccount** [comment]
Hi, all friends here is awesome website tool to make it easy and professional for all sizes

[https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=image&foreground.space.trim=1&foreground.space.pad=0.05&foreColor=rgba(255%2C%20255%2C%20255%2C%200)&backColor=rgb(255%2C%20255%2C%20255)&crop=0&backgroundShape=circle&effects=none&name=ic_launcher](url)

**Comment by GretaGri** [comment]
I work on it ;) almost done!
