### ISSUE TITLE
Create assets folder with JSON questions public database

### ISSUE THREAD

**Issue by FabioGouveia** [shoxtrem/RPGQuiz#28]
I guys, I come up with an idea to make a wonderfull and fast public database using javascript object notation technology.
The porpose of this type of database is to be fast and as I know the fastest method to fetch remote databases is using JSON technology, another porpose is to ensure that everyone can see the questions data by simply visiting the assets folder on this github webpage.
In the code context this database will give us complete controle over the internet, even if someone download the app, put up and run it... It will never be possible to commit the altered file unless someone accept the commit and merge.
This arguments were what made me choose this option instead of a regular file storage type of db, SQLite dabase or the newest Room db implementation who whoul presiste in the phone storage memory.
Any way with this database system we will have the opportunity to implemente a simple but strong and reliable database system based on javascript objects, this will also give us the chance to change this json file to the internal presistence later, the only problem I see is that in order to have this file ready for both internal, external or web presistence, it was clear that we need a responsible class for that job a decoupled class that can separate the CRUD stuff from the rest. So I come up with another idea, I thougth about creating a class called QueryUtils and a utils package to store it, this class model will have the responsability of grant us a static way to fetch data, I will open another issue for this class.

**Example of a Level object with one choice question and a character:**
```
"Beginner" : {
       {
              "question" : "Example of a question...",
              "answer" : [
                      ["example of an answer", false],    //Wrong answer
                      ["example of an answer", false],    //Wrong answer
                      ["example of an answer", true],    //Right answer
                      ["example of an answer", false],    //Wrong answer
               ],
               "character" : "https://github.com/shoxtrem/RPGQuiz/tree/master/images/game_characters/some_character_image.png"
       }
}
```

**Example of a Level object with multiple choice question:**
```
"Beginner" : {
       {
              "question" : "Example of a question...",
              "answer" : [
                      ["example of an answer", true],    //Right answer
                      ["example of an answer", false],    //Wrong answer
                      ["example of an answer", true],    //Right answer
                      ["example of an answer", false],    //Wrong answer
               ]
       }
}
```

**Example of a Level object with yes or no question:**
```
"Beginner" : {
       {
              "question" : "Example of a question...",
              "answer" : [
                      ["yes", true],    //Right answer
                      ["no", false],    //Wrong answer
               ]
       }
}
```

**Example of a Level object with a textual question:**
The possible words map as to be divided by comma with no space betwen them, we going to use them on String split method and split the strings inside it by commas.
```
"Beginner" : {
       {
              "question" : "Example of a question...",
              "answer" : [
                      ["correct answer,another correct answer,another one", true],    //Second param always true
               ]
       }
}

If you all agree with that we have to start thinking about questions and designing characters for the game.

**Comment by Bwaim** [comment]
Very good idea @FabioGouveia  !

**Comment by FabioGouveia** [comment]
Thak you Bwaim, if it's ok for you...
Can you find someone to delegate the task of drawing some background imagens for the cards just to make some level tests later tonight and someone to write some questions to test.

For the level cards background image we will need an image with three possible states, a <b>enabled</b> state, my idea is to represent this with a full color imagem with about 80% of opacity, a <b>disabled</b> state that can be represented by a gray scale image with the same 80% of opacity or a full color image with about 50% of opacity.
The last one is the <b>passed</b> state represented by a imagem that in some way convey this feeling.
For the questions will be nice for tests at least three questiona, one textual, another one for multiple choice one answer, another for multiple answer and for the sake of tests a yes or no question.

**Comment by Bwaim** [comment]
Hi Fabio, can you ask on slack that you need help for this ? I don't have access now to slack.

**Comment by FabioGouveia** [comment]
Ok Fabien, I will do it tomorrow...
I come from work, I'm to tired...


2018-02-05 14:56 GMT+00:00 Fabien Boismoreau <notifications@github.com>:
