### ISSUE TITLE
Prototype of a reusable template activity

### ISSUE THREAD

**Issue by Bwaim** [shoxtrem/RPGQuiz#9]

**Comment by Bwaim** [comment]
I work on it.

**Comment by elbpc** [comment]
a suggestion would be to make the app in a way that allows for different stories to be added later. So instead of making an app to a single story, the app could allow for future stories to be added at a later date, or to create a larger story separated by chapters that could be added posteriorly

**Comment by Bwaim** [comment]
it's what is done.
